apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dev-kube
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /user-api/(.*)
            pathType: Prefix
            backend:
              service:
                name: user
                port:
                  number: 8080
